### ISSUE TITLE
Lý do chọn đề tài, Mục tiêu và nhiệm vụ đề tài

### ISSUE THREAD

**Issue by thanhtung3008** [thanhtung3008/DATN#3]

**Comment by hothicua** [comment]
1.	Lí do chọn đề tài
-	Ngày nay nhu cầu thực tiễn cao, việc mua sắm trực tuyến phát triển mạnh mẽ, đặc biệt trong lĩnh vực thiết bị điện tử. Việc xây dựng một website bán hàng không chỉ đáp ứng nhu cầu mua sắm của khách hàng mà còn mở ra nhiều cơ hội kinh doanh cho các doanh nghiệp.
-	Việc sử dụng công nghệ hiện đại như Al và cổng thanh toán trực tuyến tăng tính cạnh tranh cho website trong bối cảnh thương mại điện tử ngày càng phát triển. Chatbot AI ngày càng được ưa chuộng vì khả năng tương tác nhanh chóng và hỗ trợ khách hàng 24/7, chatbot có thể giúp trả lời câu hỏi thường gặp, tư vấn sản phẩm, giải quyết các vấn đề nhỏ, giúp nâng cao trải nghiệm người dùng và giảm tải cho bộ phận chăm sóc khách hàng. VNPay và MoMo là một trong những cổng thanh toán phổ biến và được tin dùng tại Việt Nam, giúp khách hàng thực hiện các giao dịch một cách tiện lợi và an toàn.
2.	Mục tiêu và nhiệm vụ đề tài
          Mục tiêu: 
-	Hoàn thành được sản phẩm và đồ án tốt nghiệp
-	Xây dựng website với thiết kế giao diện thân thiện, dễ sử dụng.Phát triển các chức năng cơ bản của một website bán hàng như: tìm kiếm sản phẩm, quản lí giỏ hàng.
-	Xây dựng một chatbot AI có khả năng tương tác tự nhiên với khách hàng, trả lời các câu hỏi liên quan đến sản phẩm, hỗ trợ khách hàng trong quá trình mua sắm.
-	Kết nối website với cổng thanh toán VNPay, Momo để đảm bảo quá trình thanh toán diễn ra an toàn, nhanh chóng và tiện lợi.
Nhiệm vụ:
-	Chọn các công nghệ phù hợp để xây dựng website, chatbot và tích hợp cổng thanh toán.
-	Thiết kế giao diện người dùng (UI) và trải nghiệm người dùng (UX) cho website.
-	Lập trình backend và frontend cho website
-	Xây dựng mô hình ngôn ngữ cho chatbot, tích hợp vào website và huấn luyện chatbot.
-	Kết nối website với cổng thanh toán VNPay, Momo đảm bảo an toàn thông tin.
-	Kiểm thử, sửa lỗi và tối ưu hóa website
